### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [zaraco/url-path-generator#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by zaraco** [comment]
Hello, Thanks for your suggestion. 
Yes, I am interested in it, you can write. It would be great.

**Comment by zaraco** [comment]
> If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by geopic** [comment]
Awesome, I'll start on it now :+1:
